---
sudo: required
language: python
env:
  - MOLECULE_SCENARIO=centos
  - MOLECULE_SCENARIO=debian
  - MOLECULE_SCENARIO=ubuntu
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - virtualenv --python=$(which python2.7) .venv
  - source .venv/bin/activate
  - pip install --no-deps -r tests/test-requirements.txt
script:
  - python --version
  - ansible --version
  - molecule --version
  - molecule test --scenario-name ${MOLECULE_SCENARIO}
branches:
  only:
    - master
    - stable
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
