---
sudo: required
language: python
env:
  - MOLECULE_SCENARIO=centos
  - MOLECULE_SCENARIO=debian
  - MOLECULE_SCENARIO=ubuntu
services:
  - docker
install:
  - pip install -r molecule/requirements.txt
script:
  - python --version
  - ansible --version
  - molecule --version
  - molecule test --scenario-name ${MOLECULE_SCENARIO}
# branches:
#   only:
#     - master
#     - stable
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
