---
- name: Install Gotty systemd unit file
  template:
    src: gotty.service.j2
    dest: /etc/systemd/system/gotty.service
  when: ansible_service_mgr == 'systemd'

- name: Start Gotty service
  systemd:
    state: started
    enabled: true
    name: gotty
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'
